---
title: "Degree Completions by Level and Subgroup"
format: 
  html:
    include-in-header: 
      - text: 
          <link rel="icon" href="icons8-graduation-cap-30.png" type="image/png"/>
embed-resources: true
execute: 
  echo: false
---

```{r include=FALSE}
# Install the following packages if necessary
# install.packages(c("tidyverse", "plotly", "DT"))

# Import libraries
library(tidyverse)
library(plotly)
library(DT)

# Import data
df_gender <- read_csv("data_gender.csv")
df_citz <- read_csv("data_citz.csv")

# Function to produce bar charts
plotFunction <- function(data, degreeLevel) {
  plot_ly(
    data %>% filter(Level == degreeLevel),
    x = ~Year,
    y = ~Degrees,
    color = ~Group,
    type = "bar"
  ) %>%
    layout(
      xaxis = list(title = "Fiscal Year"),
      yaxis = list(title = "Degrees Awarded"),
      barmode = "stack"
    )
}

# Function to produce tables
tableFunction <- function(data) {
  data %>%
    pivot_wider(names_from = Group, values_from = Degrees) %>%
    mutate(Total = rowSums(pick(-Year, -Level), na.rm = TRUE)) %>%
    arrange(desc(Year), Level) %>%
    datatable(rownames = FALSE, options = list(pageLength = 5)) %>%
    formatRound(columns = 3:5, digits = 0)
}
```


## Completions by Gender

::: {.panel-tabset}

### Associate's

```{r}
plotFunction(data = df_gender, degreeLevel = "Associates")
```


### Bachelor's

```{r}
plotFunction(data = df_gender, degreeLevel = "Bachelors")
```


### Master's

```{r}
plotFunction(data = df_gender, degreeLevel = "Masters")
```


### PhD

```{r}
plotFunction(data = df_gender, degreeLevel = "PhD")
```

:::

```{r}
tableFunction(data = df_gender)
```



## Completions by Citizenship Status

::: {.panel-tabset}

### Associate's

```{r}
plotFunction(data = df_citz, degreeLevel = "Associates")
```


### Bachelor's

```{r}
plotFunction(data = df_citz, degreeLevel = "Bachelors")
```


### Master's

```{r}
plotFunction(data = df_citz, degreeLevel = "Masters")
```


### PhD

```{r}
plotFunction(data = df_citz, degreeLevel = "PhD")
```

:::

```{r}
tableFunction(data = df_citz)
```
<br>
*Source: IPEDS Degree Completions Complete Data Files, FY 2011-24*
